Strings.INFO_TAG = "[Info] "
Strings.WARN_TAG = "[Warning] "
Strings.ERR_TAG = "[Error] "
Strings.INFO_MOD_LOADED = "Mod Loaded: " .. Ext.Mod.GetMod(ToppleTheWeave.UUID).Info.Name
Strings.INFO_VOLO_IS_NOW_DEAD =
"With this character's death, the threads of the Weave have been severed. Restore a saved game to restore the Weave, or persist in the doomed world you have created."
Strings.INFO_MOD_LOADED_ALIVE = "The Weave ripples gently around you..."
Strings.INFO_MOD_LOADED_DEAD = "The Weave races against your skin, like a storm come to land..."

Strings.MSG_VOLATILE_FORCE = "Magic churns around you. You struggle for control over the spell you have cast as raw Weave pours out."
Strings.MSG_YOU_DIED = "The Weave rips through you, killing you instantly."
Strings.MSG_REMOVE_TADPOLE = "The Weave pours into your brain, weakening any unwelcome passengers."
Strings.MSG_GAINED_MONEY = "As magical wind flurries past, your purse feels heavier."
Strings.MSG_NO_MONEY = "You feel a strong wind flow into your purse."
Strings.MSG_LOST_MONEY = "As magical wind flurries past, your purse feels lighter."
Strings.MSG_END_TURN = "The moment passes before it has even begun."
Strings.MSG_CREATE_SURFACE = "The excess energy pouring out of the weave forms a surface of magical effect beneath you."
Strings.MSG_CREATE_PUDDLE = "The excess energy pouring out of the weave forms a pool of magical effect beneath you."
Strings.MSG_UNEQUIP = "As your spell unleashes, a telekinetic force puts your weapon away."
Strings.MSG_RESET_COOLDOWN = "The raw magical energy bursting past brings with it a feeling of renewal."
Strings.MSG_DESUMMON = "The beings you have summoned, if any, are sucked back through your spell, into the Weave once more."
Strings.MSG_STATUS = "You are struck by the coursing energy around you, afflicted with a status of magical origin."
Strings.MSG_EXPLOSION = "The Weave concentrates into your spell, exploding outward around you."
Strings.MSG_UNLEASHED_PROJECTILE = "As your Spell fires at the enemy, more Spells shift through the Weave. Toward you."
Strings.MSG_UNLEARN_SPELL = "No sooner than your spell left your lips did it also leave your brain, for good."
Strings.MSG_VOLATILE_FORCE_DAMAGE_TYPE = "As your spell strikes its target, the churning of the Weave permanently shifts the type of damage it will deal the next time it is cast."